name: quan_ly_cha_con
description: "Ứng dụng quản lý cha con - Child Tracker App với MVVM Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
#  map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_database: ^12.1.0
  firebase_storage: ^13.0.4

  # State Management
  provider: ^6.1.0
#Location
  location: ^7.0.0
  # Local Storage
  shared_preferences: ^2.2.2

  # Networking (tùy chọn)
  http: ^1.1.0

  # Location Services (cho tracking)
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3

  # Date & Time
  intl: ^0.19.0

  # Logging
  logger: ^2.0.1

  # Notifications (tùy chọn)
  firebase_messaging: ^16.0.4

  # Image Picker (cho avatar)
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Testing
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true