name: quan_ly_cha_con
description: "Ứng dụng quản lý cha con - Child Tracker App với MVVM Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Map
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Firebase (đồng bộ major)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_database: ^12.1.0
  firebase_storage: ^13.0.4
  cloud_firestore: 6.1.0
  firebase_messaging: ^16.0.4

  # State management
  provider: ^6.1.2

  # E2EE / Security
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3

  # Location background
  location: ^8.0.1
  geolocator: ^14.0.2

  # Local
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.1
  image_picker: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  permission_handler: ^12.0.1

  # Testing
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true